### ISSUE TITLE
Add compile time info to benchmarks

### ISSUE THREAD

**Issue by unihernandez22** [jabbalaci/SpeedTests#13]

**Comment by jabbalaci** [comment]
This project is so small that compilation is not an issue. Thanks for the tip but I don't plan to do this.

**Comment by jabbalaci** [comment]
Oh, I see why you wanted to see the compile times. Because V compiles incredibly fast according to its docs :)

**Comment by unihernandez22** [comment]
Yeah, but C compiles faster.

**Comment by unihernandez22** [comment]
The docs says that V compiles fast, buy without any optimitation. With `-prod` it is slower.

**Comment by unihernandez22** [comment]
But it's true that the V compiler is really light.

**Comment by unihernandez22** [comment]
I will use this issue for showing you this:
![image](https://user-images.githubusercontent.com/62044675/97391008-ee8bf500-18bc-11eb-8c45-4dd72ca6cc87.png)

**Comment by unihernandez22** [comment]
I will use this issue for showing you this:
![image](https://user-images.githubusercontent.com/62044675/97391045-0c595a00-18bd-11eb-969d-f807bdc8f128.png)

**Comment by unihernandez22** [comment]
1.22 seconds!!

**Comment by jabbalaci** [comment]
What do you want to show with this? Add a cover text too in which you explain clearly what you want to show. I'm not a mind-reader.
