### ISSUE TITLE
Re-run LDC's test

### ISSUE THREAD

**Issue by uninhm** [jabbalaci/SpeedTests#15]
I did it and I got 1 second faster than C!!

![image](https://user-images.githubusercontent.com/62044675/120090847-23bf2680-c0dc-11eb-9ffe-679abb6f7b4f.png)

I didn't include clang in the ss because it was a little slower than gcc

**Comment by jabbalaci** [comment]
I re-run the C and D tests. I got results similar to the previous ones.

Well, the results can be different on various machines. I run all these tests on my home desktop machine.

**Comment by uninhm** [comment]
> I re-run the C and D tests. I got results similar to the previous ones.

With which LDC version?

**Comment by jabbalaci** [comment]
```
$ ldc2 --version         
LDC - the LLVM D compiler (1.26.0):
  based on DMD v2.096.1 and LLVM 11.1.0
  built with LDC - the LLVM D compiler (1.25.1)
  Default target: x86_64-pc-linux-gnu
  Host CPU: sandybridge
  http://dlang.org - http://wiki.dlang.org/LDC
```

**Comment by uninhm** [comment]
I have the same version but based on LLVM 12, IDK if that can do the difference

**Comment by jabbalaci** [comment]
I use Manjaro Linux. When I get this update via pacman, I will re-run the tests.

**Comment by jabbalaci** [comment]
My LLVM was updated to v12:

```
$ ldc2 --version
LDC - the LLVM D compiler (1.27.1):
  based on DMD v2.097.2 and LLVM 12.0.1
  built with LDC - the LLVM D compiler (1.27.0)
  Default target: x86_64-pc-linux-gnu
  Host CPU: sandybridge
  http://dlang.org - http://wiki.dlang.org/LDC
```
I re-run the tests for D but I got very similar results. Closing this ticket.

**Comment by uninhm** [comment]
I still get D (LDC) 30% faster than C (GCC)

**Comment by uninhm** [comment]
30% is a big difference, idk why you don't get the same results

**Comment by jabbalaci** [comment]
What's the specification of your machine? Mine is in the README.

**Comment by uninhm** [comment]
Intel i5-8250U (8) 3.4GHz
