### ISSUE TITLE
Optimize python3_with_nim/rust

### ISSUE THREAD

**Issue by uninhm** [jabbalaci/SpeedTests#35]
### Proposal

[Here](https://github.com/jabbalaci/SpeedTests/blob/master/python3_with_nim/main.py#L12) and [here](https://github.com/jabbalaci/SpeedTests/blob/master/python3_with_rust/main.py#L10) it would be a little bit faster to do
```python
for n in filter(is_munchausen, range(0, N)):
    print(n)
```

### Reason
The `filter` function is implemented in C, this is why filtering is faster. When filtering, you will execute the loop body only 4 times. The less you use Python, faster is the program.

Edit: I got about a 30% optimization when I tried this with the Nim version.

**Comment by jabbalaci** [comment]
Thank you!

However, I would like to keep all the implementations similar, and every other code uses a for loop that is executed 440 million times. To keep the comparisons fair, I would keep it that way everywhere.

**Comment by uninhm** [comment]
@jabbalaci Ok, then wouldn't it be faster declaring a Nim/Rust function print_munchausen and calling it from Python? That would still do the entire loop but not in Python.

**Comment by jabbalaci** [comment]
It would be faster but then everything would happen in Nim / Rust. My idea was to implement just the testing function in Nim / Rust and call that from Python.
