### ISSUE TITLE
clang is much faster than gcc for C++ speedtest

### ISSUE THREAD

**Issue by NK01** [jabbalaci/SpeedTests#39]
I have tried the c++ source code to verify if clang and gcc are producing similar results, but I have found that clang is much faster than gcc, please test it again if possible.

All the tests were run on my laptop machine (Intel Core i7-8750H CPU @ 2.20GHz (3.90GHz turbo) with 6 CPU cores) using OpenSuSe Linux, the time was measured using inbuilt bash command `time`:
`time ./main`, which produces output like this:

![image](https://github.com/jabbalaci/SpeedTests/assets/52008914/00be8b94-0d0c-411a-bcc1-f3a4d13b5829)

## C++
- g++ (GCC) 13.2.1
- clang version 17.0.6
- Benchmark date: 2024-01-12 [yyyy-mm-dd]

| Compilation  | Runtime (sec) | EXE (bytes) |
| ------------- | ------------- | ------------- |
| `g++ -O3 --std=c++2a main.cpp -o main`  | 3.45 | 20480 |
| `clang++ -O3 --std=c++2a main.cpp -o main`  | 2.47  | 19576 |

**Comment by jabbalaci** [comment]
Thanks. I've re-tested C++ and got similar results to yours. The C++ part was updated.
