### ISSUE TITLE
 Why do you do warmup runs? 

### ISSUE THREAD

**Issue by allanwind** [jabbalaci/SpeedTests#42]
Usually, it's a concession to manage languages to not make them look horrible with a 30s start-up time or whatever.  I's only really applicable if you run a server that you warmup before taking traffic.  Your application is not a server.   In any case, I suggest you explain why the warmups in the README.

**Comment by jabbalaci** [comment]
I reduced the number of warmup runs to 1 and the number of real tests to 2. I think a warmup run is necessary for a fair test. When I run these tests, I close all applications and leave just a terminal open. During the warmup run, things can calm down.
