### ISSUE TITLE
tests with Mojo

### ISSUE THREAD

**Issue by peppelinux** [jabbalaci/SpeedTests#49]
WDYT about adding in the tests also mojo lang?

https://github.com/modularml/mojo?tab=readme-ov-file

**Comment by jabbalaci** [comment]
Send a PR. And a description (or a link) in a comment would be useful about how to install Mojo locally on Linux.

**Comment by jabbalaci** [comment]
If someone sends a PR, I can merge it. But I won't do it myself.

**Comment by jabbalaci** [comment]
Mojo was added, see https://github.com/jabbalaci/SpeedTests/pull/60
