### ISSUE TITLE
Rerun Crystal and Odin benchmarks

### ISSUE THREAD

**Issue by BigBoyBarney** [jabbalaci/SpeedTests#59]
Hi! Could you perhaps rerun the Crystal and Odin benchmarks? Both are comparatively new languages that still change / are optimised, and the latest results are from 2022 using old versions.

In my testing, Odin in particular was significantly faster than the results in the repo.
![image](https://github.com/user-attachments/assets/624552f3-36e1-49f1-b63c-ece60e538ea4)

Cheers!

**Comment by jabbalaci** [comment]
Thanks for the suggestion. I re-run the two tests. My results are the following:

* Crystal became slower than 2 years ago.
* However, the build time of Crystal is acceptable now (1.5 sec). 2 years ago it was almost 13 seconds.
* Odin has improved a lot, it was much faster than 2 years ago. Now it's similar to C.

**Comment by BigBoyBarney** [comment]
Thank you!
The crystal results seem very odd / wrong to me. As you can see on my tests, it's almost identical to Go and Odin (and around 15%-25% slower than Rust, C and Zig on my machine). :thinking: 

Compile times should still be very long, it might have done some caching from the previous compilation.

**Comment by jabbalaci** [comment]
I edited the notes on Crystal. Yes, it's similar to Go.

I executed the tests just like 2 years ago. This time I got this result.
